In [1]:
import numpy as np
import pandas as pd
import warnings
from my_static_data import *

In [2]:
pd.set_option('display.float_format', '{:.1f}'.format)
# pd.reset_option('display.float_format')
# Display maximum column width:
pd.set_option('display.max_colwidth', None)
# Suppress openpyxl data validation warning
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")

In [3]:
threshold_date = pd.Timestamp('2023-06-30')

In [4]:
ptgc = pd.read_csv('1101_pt_gc_092310.csv')
ptgc[ptgc_date_columns] = ptgc[ptgc_date_columns].apply(pd.to_datetime)
ptgc[ptgc_int_columns] = ptgc[ptgc_int_columns].astype('Int64')

In [5]:
ptgcq323 = ptgc[(ptgc[ptgc_date_columns] > threshold_date).any(axis=1)]
ptgcq323

,ptgcsp,ptgcspi,rid,fcid,ptgcndx,ptgcls,ptgc1,ptgc2,ptgc3,ptgc4,ptgc5,ptgc6,ptgc7,ptgc8,ptgc9,ptgc10,ptgct,ptgcst
0,HR,1,R0591,8110050092,14,Female(30-40),2023-01-19,2023-01-26,2023-02-02,2023-08-17,2023-08-21,2023-08-24,2023-08-31,2023-09-07,2023-09-14,2023-09-21,11,0
1,HR,2,R0553,8110050084,14,Female(30-40),2023-01-19,NaT,2023-02-02,2023-08-17,NaT,NaT,NaT,NaT,NaT,NaT,4,-1
2,HR,3,R0574,8110080007,14,Female(30-40),2023-01-19,2023-01-26,2023-02-02,2023-08-17,2023-08-21,2023-08-24,2023-08-31,2023-09-07,2023-09-14,2023-09-21,11,0
4,HR,5,R0573,8110080008,14,Female(30-40),2023-01-19,2023-01-26,2023-02-02,2023-08-17,2023-08-21,2023-08-24,2023-08-31,2023-09-07,2023-09-14,NaT,10,0
5,HR,6,R0290,8110020085,14,Female(30-40),2023-01-19,2023-01-26,2023-02-02,2023-08-17,2023-08-21,2023-08-24,2023-08-31,2023-09-07,2023-09-14,2023-09-21,11,0
6,HR,7,R0518,8110090004,14,Female(30-40),2023-01-19,2023-01-26,2023-02-02,2023-08-17,2023-08-21,2023-08-24,2023-08-31,2023-09-07,2023-09-14,2023-09-21,11,0
7,HR,8,R0540,8110050091,14,Female(30-40),2023-01-19,2023-01-26,2023-02-02,2023-08-17,2023-08-21,2023-08-24,2023-08-31,2023-09-07,2023-07-14,2023-09-21,11,0
9,HR,10,R0298,8110020089,14,Female(30-40),NaT,NaT,NaT,2023-08-17,NaT,2023-08-24,2023-08-31,NaT,2023-09-14,2023-09-21,6,0
10,HR,11,R0497,8110020115,12,Female(40-50),2023-01-16,2023-01-23,2023-01-30,2023-08-07,2023-08-14,2023-08-17,2023-08-21,2023-08-28,2023-09-04,2023-09-11,11,0
11,HR,12,R0333,8110020107,12,Female(40-50),2023-01-16,2023-01-23,2023-01-30,NaT,NaT,NaT,NaT,NaT,2023-09-04,2023-09-11,6,0
12,HR,13,R0501,8110020120,12,Female(40-50),2023-01-16,2023-01-23,2023-01-30,NaT,2023-08-14,2023-08-17,2023-08-21,2023-08-28,NaT,2023-09-11,9,0
13,HR,14,R0402,8110020119,12,Female(40-50),2023-01-16,2023-01-23,2023-01-30,2023-08-07,2023-08-14,2023-08-17,2023-08-21,NaT,2023-09-04,2023-09-11,10,0
14,HR,15,R0367,8110020110,12,Female(40-50),2023-01-16,2023-01-23,2023-01-30,2023-08-07,2023-08-14,2023-08-17,2023-08-21,2023-08-28,2023-09-04,2023-09-11,11,0
15,HR,16,R0353,8110020099,12,Female(40-50),2023-01-16,2023-01-23,2023-01-30,2023-08-07,2023-08-14,2023-08-17,2023-08-21,2023-08-28,2023-09-04,2023-09-11,11,0
16,HR,17,R0300,8110020093,12,Female(40-50),2023-01-16,2023-01-23,2023-01-30,NaT,2023-08-14,2023-08-17,2023-08-21,2023-08-28,2023-09-04,2023-09-11,10,0
17,HR,18,R0391,8110050067,12,Female(40-50),2023-01-16,2023-01-23,2023-01-30,2023-08-07,2023-08-14,2023-08-17,2023-08-21,2023-08-28,2023-09-04,2023-09-11,11,0
18,HR,19,R0348,8110020097,12,Female(40-50),2023-01-16,2023-01-23,2023-01-30,2023-08-07,NaT,2023-08-17,2023-08-21,2023-08-28,2023-09-04,NaT,8,0
19,HR,20,R0441,8110050063,12,Female(40-50),2023-01-16,2023-01-23,2023-01-30,NaT,NaT,NaT,2023-08-21,2023-08-28,2023-09-04,2023-09-11,7,0
82,HJ,73,R0473,8110050083,13,Female(20-30),2023-01-17,2023-01-24,2023-01-31,2023-08-08,2023-08-15,2023-08-22,2023-08-29,2023-09-05,2023-09-12,2023-09-19,11,0
83,HJ,74,R0117,8110050055,13,Female(20-30),2023-01-17,2023-01-24,2023-01-31,2023-08-08,2023-08-15,2023-08-22,2023-08-29,2023-09-05,2023-09-12,2023-09-19,11,0
84,HJ,75,R0444,8110050070,13,Female(20-30),2023-01-17,2023-01-24,2023-01-31,2023-08-08,2023-08-15,2023-08-22,2023-08-29,2023-09-05,2023-09-12,2023-09-19,11,0
85,HJ,76,R0508,8110050082,13,Female(20-30),2023-01-17,2023-01-24,2023-01-31,2023-08-08,2023-08-15,2023-08-22,2023-08-29,2023-09-05,2023-09-12,2023-09-19,11,0
87,HJ,78,R0571,8110080004,13,Female(20-30),2023-01-17,2023-01-24,2023-01-31,2023-08-08,2023-08-15,2023-08-22,2023-08-29,2023-09-05,2023-09-12,2023-09-19,11,0
88,HJ,79,R0451,8110090005,13,Female(20-30),2023-01-17,2023-01-24,2023-01-31,2023-08-08,2023-08-15,2023-08-22,2023-08-29,2023-09-05,2023-09-12,2023-09-19,11,0
89,HJ,80,R0613,8110090006,13,Female(20-30),2023-01-17,2023-01-24,2023-01-31,2023-08-08,2023-08-15,2023-08-22,2023-08-29,2023-09-05,2023-09-12,2023-09-19,11,0
90,HJ,81,R0460,8110090003,13,Female(20-30),2023-01-17,2023-01-24,2023-01-31,2023-08-08,2023-08-15,2023-08-22,2023-08-29,2023-09-05,2023-09-12,2023-09-19,11,0
92,HJ,83,R0485,8110020104,15,Male(40-50),2023-01-25,2023-02-01,2023-08-09,NaT,2023-08-23,2023-08-29,2023-09-06,2023-09-13,2023-09-20,2023-09-27,11,0
93,HJ,84,R0337,8110020100,15,Male(40-50),2023-01-25,2023-02-01,2023-08-09,2023-08-16,2023-08-23,2023-08-29,2023-09-06,2023-09-13,2023-09-20,2023-09-27,11,0
94,HJ,85,R0382,8110020105,15,Male(40-50),2023-01-25,2023-02-01,2023-08-09,2023-08-16,2023-08-23,2023-08-29,2023-09-06,2023-09-13,2023-09-20,2023-09-27,11,0
95,HJ,86,R0274,8110020090,15,Male(40-50),2023-01-25,2023-02-01,NaT,NaT,NaT,NaT,2023-09-06,NaT,NaT,NaT,3,-1
96,HJ,87,R0183,8110020101,15,Male(40-50),NaT,NaT,2023-08-09,2023-08-16,NaT,NaT,NaT,NaT,NaT,NaT,2,-1
97,HJ,88,R0599,8110050093,15,Male(40-50),2023-01-25,2023-02-01,2023-08-09,2023-08-16,NaT,NaT,NaT,NaT,2023-09-20,2023-09-27,4,0
98,HJ,89,R0486,8110020103,15,Male(40-50),2023-01-25,2023-02-01,NaT,NaT,2023-08-23,2023-08-29,2023-09-06,NaT,2023-09-20,2023-09-27,11,0
100,HJ,91,R0487,8110080005,15,Male(40-50),2023-01-25,2023-02-01,2023-08-09,2023-08-16,2023-08-23,2023-08-29,2023-09-06,2023-09-13,2023-09-20,2023-09-27,11,0
101,HJ,92,R0582,8110050094,15,Male(40-50),NaT,NaT,2023-08-09,NaT,NaT,2023-08-29,NaT,2023-09-13,NaT,NaT,3,-1
102,HJ,93,R0120,8110020106,15,Male(40-50),NaT,NaT,2023-08-09,2023-08-16,2023-08-23,2023-08-29,2023-09-06,2023-09-13,2023-09-20,2023-09-27,11,0

In [6]:
pt_groups = ptgcq323.groupby('ptgcndx')
pt_groups.first()

,ptgcsp,ptgcspi,rid,fcid,ptgcls,ptgc1,ptgc2,ptgc3,ptgc4,ptgc5,ptgc6,ptgc7,ptgc8,ptgc9,ptgc10,ptgct,ptgcst
ptgcndx,,,,,,,,,,,,,,,,,
12,HR,11,R0497,8110020115,Female(40-50),2023-01-16,2023-01-23,2023-01-30,2023-08-07,2023-08-14,2023-08-17,2023-08-21,2023-08-28,2023-09-04,2023-09-11,11,0
13,HJ,73,R0473,8110050083,Female(20-30),2023-01-17,2023-01-24,2023-01-31,2023-08-08,2023-08-15,2023-08-22,2023-08-29,2023-09-05,2023-09-12,2023-09-19,11,0
14,HR,1,R0591,8110050092,Female(30-40),2023-01-19,2023-01-26,2023-02-02,2023-08-17,2023-08-21,2023-08-24,2023-08-31,2023-09-07,2023-09-14,2023-09-21,11,0
15,HJ,83,R0485,8110020104,Male(40-50),2023-01-25,2023-02-01,2023-08-09,2023-08-16,2023-08-23,2023-08-29,2023-09-06,2023-09-13,2023-09-20,2023-09-27,11,0

In [11]:
pt_groups.get_group(15)

,ptgcsp,ptgcspi,rid,fcid,ptgcndx,ptgcls,ptgc1,ptgc2,ptgc3,ptgc4,ptgc5,ptgc6,ptgc7,ptgc8,ptgc9,ptgc10,ptgct,ptgcst
92,HJ,83,R0485,8110020104,15,Male(40-50),2023-01-25,2023-02-01,2023-08-09,NaT,2023-08-23,2023-08-29,2023-09-06,2023-09-13,2023-09-20,2023-09-27,11,0
93,HJ,84,R0337,8110020100,15,Male(40-50),2023-01-25,2023-02-01,2023-08-09,2023-08-16,2023-08-23,2023-08-29,2023-09-06,2023-09-13,2023-09-20,2023-09-27,11,0
94,HJ,85,R0382,8110020105,15,Male(40-50),2023-01-25,2023-02-01,2023-08-09,2023-08-16,2023-08-23,2023-08-29,2023-09-06,2023-09-13,2023-09-20,2023-09-27,11,0
95,HJ,86,R0274,8110020090,15,Male(40-50),2023-01-25,2023-02-01,NaT,NaT,NaT,NaT,2023-09-06,NaT,NaT,NaT,3,-1
96,HJ,87,R0183,8110020101,15,Male(40-50),NaT,NaT,2023-08-09,2023-08-16,NaT,NaT,NaT,NaT,NaT,NaT,2,-1
97,HJ,88,R0599,8110050093,15,Male(40-50),2023-01-25,2023-02-01,2023-08-09,2023-08-16,NaT,NaT,NaT,NaT,2023-09-20,2023-09-27,4,0
98,HJ,89,R0486,8110020103,15,Male(40-50),2023-01-25,2023-02-01,NaT,NaT,2023-08-23,2023-08-29,2023-09-06,NaT,2023-09-20,2023-09-27,11,0
100,HJ,91,R0487,8110080005,15,Male(40-50),2023-01-25,2023-02-01,2023-08-09,2023-08-16,2023-08-23,2023-08-29,2023-09-06,2023-09-13,2023-09-20,2023-09-27,11,0
101,HJ,92,R0582,8110050094,15,Male(40-50),NaT,NaT,2023-08-09,NaT,NaT,2023-08-29,NaT,2023-09-13,NaT,NaT,3,-1
102,HJ,93,R0120,8110020106,15,Male(40-50),NaT,NaT,2023-08-09,2023-08-16,2023-08-23,2023-08-29,2023-09-06,2023-09-13,2023-09-20,2023-09-27,11,0